import crypto from 'node:crypto';
const REPO='afiss859-eng/sira-website';
const STORE='data/orange-money-control.json';
const EMAIL=process.env.ADMIN_EMAIL||'sawadogoafis125@gmail.com';
function auth(req){const h=String(req.headers?.authorization||'');if(!h.startsWith('Basic ')||!process.env.ADMIN_PASSWORD)return false;try{const d=Buffer.from(h.slice(6),'base64').toString('utf8');const i=d.indexOf(':');return i>0&&d.slice(0,i)===EMAIL&&d.slice(i+1)===process.env.ADMIN_PASSWORD}catch{return false}}
function gh(){if(!process.env.GITHUB_TOKEN)throw new Error('GITHUB_TOKEN manquant.');return{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}}
const url=()=>`https://api.github.com/repos/${REPO}/contents/${STORE}`;
async function read(){const r=await fetch(url(),{headers:gh(),cache:'no-store'});if(r.status===404)return{data:{version:1,apps:[]},sha:null};if(!r.ok)throw new Error(`GitHub GET ${r.status}`);const f=await r.json();return{data:JSON.parse(Buffer.from(f.content,'base64').toString('utf8')),sha:f.sha}}
async function write(data,sha,message){const body={message,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64'),branch:'main'};if(sha)body.sha=sha;const r=await fetch(url(),{method:'PUT',headers:{...gh(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`GitHub PUT ${r.status}`)}
function key(){const x=crypto.randomBytes(12).toString('hex').toUpperCase();return `SIRA-OM-${x.slice(0,4)}-${x.slice(4,8)}-${x.slice(8,12)}`}
export default async function handler(req,res){try{const action=String(req.query?.action||'overview');const current=await read();const data=current.data||{version:1,apps:[]};data.apps=Array.isArray(data.apps)?data.apps:[];
if(action==='validate'&&req.method==='POST'){const k=String(req.body?.key||'').trim();const deviceId=String(req.body?.deviceId||'').trim();const app=data.apps.find(x=>x.licenseKey===k);if(!app)return res.status(401).json({valid:false,error:'Licence Orange Money inconnue.'});if(app.status!=='ACTIVE')return res.status(401).json({valid:false,error:`Licence ${app.status.toLowerCase()}.`,revoked:true});if(app.expiresAt&&new Date(app.expiresAt)<new Date())return res.status(401).json({valid:false,error:'Licence expirée.',expired:true});const devices=Array.isArray(app.deviceIds)?app.deviceIds:[];if(!devices.includes(deviceId)){if(devices.length>=Math.max(1,Number(app.maxDevices)||1))return res.status(401).json({valid:false,error:'Quota d’appareils atteint.'});app.deviceIds=[...devices,deviceId];await write(data,current.sha,`orange-money: register device ${deviceId}`)}return res.status(200).json({valid:true,license:{key:app.licenseKey,appName:app.appName,merchantName:app.merchantName,status:app.status,maxDevices:app.maxDevices,usedCount:(app.deviceIds||[]).length,features:app.features||{},themeColor:app.themeColor||'#F97316'},commands:app.commands||[]})}
if(!auth(req))return res.status(401).json({ok:false,error:'Authentification administrateur requise.'});
if(req.method==='GET')return res.status(200).json({ok:true,apps:data.apps.map(({licenseKey,merchantName,status,maxDevices,appName,features,deviceIds})=>({licenseKey,merchantName,status,maxDevices,appName,features,deviceCount:(deviceIds||[]).length}))});
if(action==='create-license'){const licenseKey=key();const app={licenseKey,merchantName:String(req.body?.merchantName||'Commerce SIRA'),appName:String(req.body?.appName||'SIRA Orange Money'),status:'ACTIVE',maxDevices:Math.max(1,Math.min(20,Number(req.body?.maxDevices)||1)),expiresAt:req.body?.expiresAt?new Date(req.body.expiresAt).toISOString():null,themeColor:String(req.body?.themeColor||'#F97316'),features:{offline:true,commissionReport:true,history:true,export:false,ai:false},deviceIds:[],commands:[],createdAt:new Date().toISOString()};data.apps.unshift(app);await write(data,current.sha,`orange-money: create ${licenseKey}`);return res.status(201).json({ok:true,licenseKey})}
if(action==='set-status'){const app=data.apps.find(x=>x.licenseKey===String(req.body?.licenseKey||''));const status=['ACTIVE','SUSPENDED','REVOKED'].includes(req.body?.status)?req.body.status:null;if(!app||!status)return res.status(400).json({ok:false,error:'Licence ou statut invalide.'});app.status=status;await write(data,current.sha,`orange-money: status ${app.licenseKey} ${status}`);return res.status(200).json({ok:true})}
if(action==='configure'){const app=data.apps.find(x=>x.licenseKey===String(req.body?.licenseKey||''));if(!app)return res.status(404).json({ok:false,error:'Licence introuvable.'});if(req.body?.appName!==undefined)app.appName=String(req.body.appName).slice(0,120);if(req.body?.themeColor!==undefined)app.themeColor=String(req.body.themeColor).slice(0,20);if(req.body?.features&&typeof req.body.features==='object')app.features={...app.features,...req.body.features};await write(data,current.sha,`orange-money: configure ${app.licenseKey}`);return res.status(200).json({ok:true})}
if(action==='command'){const app=data.apps.find(x=>(x.deviceIds||[]).includes(String(req.body?.deviceId||'')));const command=['LOCK_APP','FORCE_SYNC','SHOW_MESSAGE'].includes(req.body?.command)?req.body.command:null;if(!app||!command)return res.status(400).json({ok:false,error:'Appareil ou commande invalide.'});app.commands=[...(app.commands||[]),{id:crypto.randomBytes(8).toString('hex'),command,payload:req.body?.payload||{},createdAt:new Date().toISOString()}];if(command==='LOCK_APP')app.status='SUSPENDED';await write(data,current.sha,`orange-money: ${command}`);return res.status(201).json({ok:true})}
return res.status(400).json({ok:false,error:'Action inconnue.'})}catch(e){console.error('SIRA Orange Money control',e);return res.status(500).json({ok:false,error:'Erreur du centre de contrôle Orange Money.'})}}
